### ISSUE TITLE
Command to get CEA standings or matchup for upcoming week

### ISSUE THREAD

**Issue by natestrel** [tynidev/tynibot#33]
https://1ebv8yx4pa.execute-api.us-east-1.amazonaws.com/prod/tournaments is a good place to start. 

where res.Game.id == "rl" && res.Current == true should get the correct tourney then go from there for other api calls to get tournemnt standings/team matchups, etc.

**Comment by bradleyholloway** [comment]
Added basic !cea funcitonality. https://github.com/tynidev/tynibot/pull/34

Further enhancements include:
1. Migrate to slash commands
2. Add ability to match teams by org, not just single team names.
3. Fixes to the https://www.nuget.org/packages/PlayCEA.RLClient/ in how playoff + regular season are handled.
